### ISSUE TITLE
Usage questions: SSL enabled on HA required, work with docker image of HA

### ISSUE THREAD

**Issue by deepcoder** [home-assistant/home-assistant-cli#139]
Does hass-cli require that HTTPS access be enabled in order to work. Is is possible to use without HTTPS enabled on HA?

Does hass-cli only work with hass.io based HA, or will it work with docker image file of HA?

Thx.

**Comment by maxandersen** [comment]
it should work with any homeassistant accessible over http or https.

does not matter if in hass.io or not.

in short - if your browser can access homeassistant then hass-cli can too.
