### ISSUE TITLE
warning report

### ISSUE THREAD

**Issue by aram535** [home-assistant/home-assistant-cli#142]
# hass-cli  --version 
hass-cli, version 0.4.4

# hass-cli config whitelist-dirs
Trying to locate Home Assistant on                local network...
Exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/zeroconf.py", line 1179, in handle_read
    data, (addr, port) = socket_.recvfrom(_MAX_MSG_ABSOLUTE)
OSError: [Errno 9] Bad file descriptor
Found and using http://192.168.1.4:8123 as server
DIRECTORY
/config/www

# pip3.6 list | grep -i zero 
zeroconf (0.21.3)

**Comment by maxandersen** [comment]
@aram535, i'm not fully grokking what you are reporting here - can you add a bit more details ? Thank you!

**Comment by aram535** [comment]
@maxandersen It's throwing an exception.  If it doesn't mean anything then maybe wrap the call in a try block?

**Comment by maxandersen** [comment]
Can you run the same command with -x then it will get a full stacktrace so I can more easily pinpoint it. 

I assume this does not happen when you explicitly specify the server url?

**Comment by aram535** [comment]
Ummm ... it fixed itself. 

I ran it like 4 times yesterday trying to figure out where the break was ... and haven't touched it or even logged into it since.

```
# hass-cli -x config whitelist-dirs
Trying to locate Home Assistant on                local network...
Found and using http://192.168.1.4:8123 as server
DIRECTORY
/config/www

# hass-cli config whitelist-dirs   
Trying to locate Home Assistant on                local network...
Found and using http://192.168.1.4:8123 as server
DIRECTORY
/config/www

```
