### ISSUE TITLE
Columns not applied to entity get command

### ISSUE THREAD

**Issue by Dobli** [home-assistant/home-assistant-cli#150]
**Version used:** 0.4.4

**Problem:**
The _--columns_ parameter is not applied to the `entity get` command only for `entity list`.
I try to create an i3 status bar entry for delaying trains and only need the state value, therefore tried to filter by columns but it didn't work.
Additionally it would be nice to have this as a direct option (e.g. `-q` for _quiet_ output with only the state).

Otherwise, great tool, using it already with rofi to quickly toggle the lights in my flat ;).

**Comment by maxandersen** [comment]
good catch - fixed in #154 

about direct option for it something like `-o name` or `-o id` as a way to what gets output would be useful. That is mainly captured in #101
