### ISSUE TITLE
is it recommended to run in the hass virtual environment or its own?

### ISSUE THREAD

**Issue by bbrendon** [home-assistant/home-assistant-cli#153]
is it recommended to run in the hass virtual environment or its own?

Thanks.

**Comment by maxandersen** [comment]
in last 0.4 release we made a mistake on the pyyml release so there would be a mismatch in dependencies but in past and future releases you should in theory be fine. That said - if you want the least amount of surprises then a separate venv or using pipsi like : `pipsi install --python python3 homeassistant-cli` is best.

thanks for asking :)
