### ISSUE TITLE
Add an uptime command 

### ISSUE THREAD

**Issue by johntdyer** [home-assistant/home-assistant-cli#162]
An uptime command would be cool

**Comment by maxandersen** [comment]
I haven't seen that info in the HA API or UI. Maybe @fabaff knows?

**Comment by fabaff** [comment]
There is an [`uptime` sensor](https://www.home-assistant.io/components/sensor.uptime/) but the API is not exposing the uptime.

Usually the uptime is not longer than two weeks :wink:

**Comment by maxandersen** [comment]
well, then its already there (kind of :), just need to add that to configuration.yaml and you can do:

`hass-cli entity get sensor.uptime` to get the value :)
