### ISSUE TITLE
event watch json syntax - single quote vs. double quoted strings

### ISSUE THREAD

**Issue by lmamakos** [home-assistant/home-assistant-cli#168]
At least the `jq` command seems to believe that JSON text ought to have double-quoted string elements, e.g, when defining dictionary keys and values.   Sending the output of `event listen` into `jq` yields a error trying to parse the line due to the use of single-quoted string elements.

I don't know if the literal JSON strings originate inside of Home Assistant, or if home-assistant-cli constructs them?  Regardless, I think it would be _really great_ to be able to use `jq` with home-assistant-cli.

I'm using version `jq-1.5-1-a5b5cbe` of jq as installed by apt-get in my Linux Mint 19 testing VM.

**Comment by fabaff** [comment]
The data is coming from Home Assistant. `hass-cli` is only relaying the events to the console.

**Comment by maxandersen** [comment]
Ah, that explains why I was having issues too. Weird HA outputs that style. Anyways easy fix in #168 (thanks @fabaff) and once we enable output formatting you'll be able to get rows or yaml too.

**Comment by maxandersen** [comment]
fixed in #179
