### ISSUE TITLE
Reference env vars in help message

### ISSUE THREAD

**Issue by lmamakos** [home-assistant/home-assistant-cli#173]
It would be really useful if the help text for the `--token` and `--server` options referenced the available environment variables (`HASS_TOKEN` and `HASS_SERVER`) that can also be set up by the user.  You have to dig around a bit to discover what these are, otherwise.  This seems like one obvious place to note them; perhaps there are other places in the `--help` output that would be more consistent with existing style.

Thanks for the really wonderful tool!

**Comment by fabaff** [comment]
It's covered in the [README](https://github.com/home-assistant/home-assistant-cli/blob/dev/README.rst#setup). But if it's helps could be added to `--help`.

**Comment by lmamakos** [comment]
Thanks, that's great!  The README is great, but not obviously available if someone does `pip install homeassistant-cli`
