### ISSUE TITLE
Docker image for armhf architecture

### ISSUE THREAD

**Issue by rufik** [home-assistant/home-assistant-cli#176]
AFAIK there is no armhf version of docker image, so I cannot test it properly on RPi.
Could you build it please?

**Comment by maxandersen** [comment]
I haven’t done docker builds specifically for armed before. If/Can you provide a pr for it then we should be able to build it.

**Comment by rufik** [comment]
PR done. I've created dedicated dockerfile for armhf image. It uses balenalib's "python on alpine" because ease of cross-platform building. All you need is just to setup dedicated image build with some proper tag like **dev-armhf**.
It's suitable for armhf v7 architecture (like RPi 3 or OrangePI SBCs).

**Comment by maxandersen** [comment]
Thanks - now I just need to figure out how those armhf and other variations gets built. Asked at https://github.com/home-assistant/developers.home-assistant/issues/178; great if you or someone else might be able to help as I've not have much luck yet ;)

**Comment by rufik** [comment]
If you would like to setup DockerHub build, you just need to:
- enter dedicated "Docker Tag" like "armhf-dev" for example,
- enter "Dockerfile location" = Dockerfile.armhf
And  you've done :)

**Comment by maxandersen** [comment]
Yes that's what I figured but I don't have access to home assistant dockerhub ;)

@fabaff Or @balloob I'll merge this then I hope one of you can activate the build side.

**Comment by balloob** [comment]
![image](https://user-images.githubusercontent.com/1444314/52871775-aedca400-30ff-11e9-95fc-be4f7ab10380.png)

**Comment by maxandersen** [comment]
Thanks @balloob - shouldn’t there be a armhf build for the tags too ?

**Comment by rufik** [comment]
> Thanks @balloob - shouldn’t there be a armhf build for the tags too ?

And one more thing - Dockerfile.armhf is on dev branch only, so it should be merged to master branch also or docker build should be dev-armhf only from dev branch.

**Comment by maxandersen** [comment]
It goes to master when we release. But I agree would be nice to have both master and dev built.

**Comment by maxandersen** [comment]
actually already done.
