### ISSUE TITLE
One-off discovery in local network

### ISSUE THREAD

**Issue by lbischof** [home-assistant/home-assistant-cli#192]
I am running Homeassistant in Docker with `net=host` at the moment. The only reason I am doing this is because discovery only works if it is run from within the LAN. Would it be possible to run discovery locally with this tool and send the "results" to Homeassistant? Then it would be possible to only run this script on the host network when I add new devices to the network.

**Comment by maxandersen** [comment]
Not at the moment as things are setup. Interesting idea though. would be better you suggest this as a feature in homeassistsant to allow decoupled discovery.
