### ISSUE TITLE
Incompatibility in ruamel.yaml between hass 0.88 and homeassistant-cli 0.5.0

### ISSUE THREAD

**Issue by jhfreeman1** [home-assistant/home-assistant-cli#194]
Upon upgrading from hass 0.87.1 to 0.88, I received the following:

homeassistant-cli 0.5.0 has requirement ruamel.yaml==0.15.85, but you'll have ruamel-yaml 0.15.88 which is incompatible.

Hope this is helpful  Thank you for all of the work you have done.

**Comment by maxandersen** [comment]
0.6 was released that has same ruamel version as latest hass. 

Note: often pip is a bit aggressive on reporting incompatible. IE. In this case I don't believe there are any functional diff.
