### ISSUE TITLE
add zha to configuration.yaml then permit join devices

### ISSUE THREAD

**Issue by zamashal** [home-assistant/home-assistant-cli#203]
I would like to add zha to the configuration.yaml file then permit zigbee devices to join/pair. This is how I usually use home assistant UI, but the UI seems to be eating up my memory and hopefully hass-cli would be better. How do I do that with hass-cli?

**Comment by maxandersen** [comment]
Not following. If you are adding the setup to configuration. Yaml then you aren't using the home assistant UI.

I haven't tried using ha zigbee integration but if you just need calling a service then you can do that with has cli. Just need to find is name in UI or via service list

**Comment by maxandersen** [comment]
@zamashal can you provide more info/context as otherwise I would like to close this issue ?
