### ISSUE TITLE
bellows 0.7.0 has requirement click-log==0.2.0, but you'll have click-log 0.3.2

### ISSUE THREAD

**Issue by zamashal** [home-assistant/home-assistant-cli#204]
During the execution of the command:
`pip install homeassistant-cli`
I saw the following error
```
bellows 0.7.0 has requirement click-log==0.2.0, but you'll have click-log 0.3.2 which is incompatible.
bellows-homeassistant 0.7.1 has requirement click-log==0.2.0, but you'll have click-log 0.3.2 which is incompatible.
```

**Comment by maxandersen** [comment]
Looks like bellows uses old version and should get updated it is dependencies to remove the warning.

**Comment by maxandersen** [comment]
Solution Is to install in a separate virtual environment. Cli can't fix dependency issues in unrelated projects.
