### ISSUE TITLE
Seriously.

### ISSUE THREAD

**Issue by robotsandcake** [home-assistant/home-assistant-cli#228]
I know that this isn't a bug report or anything similar, but I do have an issue and I wanted to get this message straight to the devs. Otherwise I would have had to have said something in Discord and people would have inevitably started asking "so if you're quadriplegic, how you using your computer?". Because nobody wants to see me cry at that question again.<sup>1</sup>

ANYWAY, little command line tool just made the life of this slightly tubby,  quadriplegic, pretend hacker, dashingly handsome and totally obsessed Home Assistant user about 17.3m % easier. 

Thank you.

(Feel free to delete this as completely off topic, natch!)

<sup>1</sup> That came across as a way meaner than I meant it to. I mean, I do get it; If you're a geek like all of you clearly are it can be interesting to find out how somebody operates as a developer, roboticist and totally not a Twitter Troll just using one index finger and head movements. It's just sometimes... But having said that, feel free to ask anything you like! :-)

**Comment by maxandersen** [comment]
Would love to hear more specifics about what brought those 17.3m % life enhancement :)

**Comment by maxandersen** [comment]
Closing this as not an open issue but do feel free to share more - I love real usecases over my own pretend-real ones ;)

**Comment by robotsandcake** [comment]
Would you like to hear them, or was that rhetorical? Shall I email you rather than clutter up the issues? If so, where would you like me to message?

 I would really like to know how to get the state of  `sensor.something ` from out of the database from the minute it was put in there, but can't quite work out how to do it. I can get the state right now which is GPS coordinates, but I would like a big long list of them all if you see what I mean?

**Comment by maxandersen** [comment]
> Would you like to hear them, or was that rhetorical? Shall I email you rather than clutter up the issues? If so, where would you like me to message?

i do like to hear them - you mail me, comment here or share on community.home-assistant.io - whatever you feel comfortable with. 

> I would really like to know how to get the state of `sensor.something ` from out of the database from the minute it was put in there, but can't quite work out how to do it. I can get the state right now which is GPS coordinates, but I would like a big long list of them all if you see what I mean?

you mean all `sensor.something` currently present like:

`$ hass-cli --columns attributes.latitude,attributes.longitude state list person.max
attributes.latitude   attributes.longitude
                  -123.45    45.43    
`
or you mean its history, like:

`$ hass-cli --columns attributes.latitude,attributes.longitude state history person.max` 

if the latter then I'm actually seeing what looks like a bug in recent homeassistant versions that it does not actually filter on the entity id. 

Is that’s your issue ?

**Comment by maxandersen** [comment]
note: seems dev branch don't have the issue of bad filtering so it should actually work doing:

`$ hass-cli --columns attributes.latitude,attributes.longitude state history person.max`

note, that this is not a fast operation - depends very much of what kind of database and how long history you are keeping.

if you want to do more history based queries I think using something like the data portal approach using jupyter - see https://data.home-assistant.io/docs/quick_start_index.html

at least for now as hass-cli could actually benefit from exposing something similar to make it easy to get to - but that isn't there yet.

hope that helpsl

**Comment by robotsandcake** [comment]
Sorry about the radio silence, that really does help. Thank you! :-)
