### ISSUE TITLE
"entity list" returns incorrect results

### ISSUE THREAD

**Issue by bbrendon** [home-assistant/home-assistant-cli#229]
version 0.6.0

Entity list is missing a bunch of stuff and also has stuff in it that are no longer in my system.

```
$ hass-cli entity list|wc -l
57
```

The states list in the GUI has 369 entities listed.

<5 minutes later after poking around more>

I get the feeling this is a documentation issue. I think there is confusion about what this entity list is supposed to do. It seems like the state command lists entities and their states.  The entity command is a way to edit entities?

The syntax seems confusing to me.

**Comment by maxandersen** [comment]
Before hass-cli 0.6 we (wrongly) used "entity list" to fetch info from the state-registry; it wasn't until I wanted to add support for renaming entities and assigning areas I realised that entities was managed via entity-registry. 

Thus if you read some docs from before 0.6 this confusing. But if you read the *current* docs it should all say the right thing. 

If you found something that is not updated to the right thing do point it out so it can get fixed. 

And yes, entity command list and edit entities and state command list and edit states. 

In my opinion that is better than what was there before which was flipped.

If you still think the command returns wrong info do give an example and we can dig further - be aware the entity registry can easily contain information about past equipment as homeassistant don't just forget about it in case it's just being offline and might become relevant again.

**Comment by bbrendon** [comment]
Based on what you said and what I deduced I don't think it's returning the wrong info, just the instructions are confusing. It seems like ultimately somehow the syntax could change to make it more clear. I'm not sure how exactly though.

Until that is done I think a modification of the below could clear this up. Instead of saying " List all entities from Home Assistant." , how about " List all entities that can be modified in Home Assistant."

You could even add "Note: to get a list of entities use the state list".

```
 hass-cli entity
Usage: hass-cli entity [OPTIONS] COMMAND [ARGS]...

  Get info on entities from Home Assistant.

Options:
  --help  Show this message and exit.

Commands:
  list    List all entities from Home Assistant.
  rename  Rename a entity.
```

**Comment by bbrendon** [comment]
Some ideas on syntax...

Maybe "entity list" could list could be renamed to "registry list" 

Or

"entity list" returns all entities and whatever is in the registry and has a column that indicates the entity is modifiable in the registry or not.

**Comment by maxandersen** [comment]
just to clear, *all* the key operationrs works on registries (entity, state, area, etc. registries).

also, “state list” do not actually list entities, it list states associated to enities. And all entities returned by “entity list” are accessible/editable in Home Assistant - but only some have state. Thus im not sure what it will help to say “those that are editable in home assistant” because that is all of them when it comes to entities (not state), is it not ?

If you look in home assistant it actually always talks about state, not entities.

But I agree its confusing since I got caught in it myself making hass-cli and calling it “entity list” when it was wrong - thus my past blog and videos on hass-cli uses entity list where I should have been talking about state list.

**Comment by bbrendon** [comment]
I'm totally confused now.  So an entity is not the same as an entity_id ? I thought the state list was a list of entities along with their value/state?

Now I need to go digging in the docs...

**Comment by bbrendon** [comment]
I read this and it seems like entities have states.
https://developers.home-assistant.io/docs/en/entity_index.html

...I don't know what to think.

**Comment by maxandersen** [comment]
Yup, so there are there are entities (accessed and manipulated with "entity" command) which then have states (accessed and manipulated with "state" command). 

Hope that helps?

**Comment by bbrendon** [comment]
That's what I thought. Can there be entities that can not have a state?

**Comment by maxandersen** [comment]
Yeah I Believe that happens when a platform is removed or fails for some reason there could be a situation where no state is published but still info on entities found in past runs. 

Which becomes useful when the platforms works again and you then don't need to rename the entity nor reassign area.

**Comment by maxandersen** [comment]
closing as not specific issues identified (Besides past versions of hass-cli being wrong in mixing up entity and state). if you do find some docs that are mixing it up do reopen or open new issue.
