### ISSUE TITLE
Hass.io compatibility

### ISSUE THREAD

**Issue by frenck** [home-assistant/home-assistant-cli#23]
For Hass.io users the CLI is harder to get running. With a little bit of code, this CLI would probably just work out of the box for these users.

Steps to take:
- `HASS_SERVER` environment variable is absent.
- `HASS_TOKEN` environment variable is absent.
- Detect if the `HASSIO_TOKEN` environment variable is present.
- If present, use `http://hassio/homeassistant` as the server URL
- If present, use the `HASSIO_TOKEN` environment variable as the bearer token.

**Comment by maxandersen** [comment]
so what you are saying is if HASSIO_TOKEN available use a different default_server ? 

and I thought the default url for hassio is `http://hassio.local:8234` not `http://hassio/homeassistant` ?

or are you talking about if you run hass-cli *on* your hassio instance ?

**Comment by maxandersen** [comment]
fyi, I was actually considering using `http://hassio.local:8123` when only HASSIO_TOKEN present since that seem to work from wherever. Would that work for your usecase ?

**Comment by maxandersen** [comment]
Submitted PR #26 as a WIP to see if this would be nice to work with.

It uses hassio.local as the server name as I couldn't find a place where http://hassio actually worked outside hassio docker containers or directly logged into hassio - something I believe is NOT recommended/deemed relevant for most users.

 I initially thought it would be nice to have but then I realized I run with https enabled and thus this default fallback won't work anyway as neither hass nor hassio redirects http to https by default (for simplicity reasons)

do let me know what you think. I'm currently +0 on this as i'm not sure it will help that much...

**Comment by frenck** [comment]
@maxandersen The URL must be exactly `http://hassio/homeassistant`.

This URL is only available inside the Hass.io platform (e.g., inside an Hass.io SSH add-on).
SSL is not a factor here since this URL is a bridge between Home Assistant and the Hass.io Supervisor that handles the connection differently. This URL will always work, even with SSL enabled.

**Comment by frenck** [comment]
Working example (current workaround for me):

https://github.com/hassio-addons/addon-ssh/blob/master/ssh/rootfs/root/.zshrc#L96

**Comment by maxandersen** [comment]
yeah so thinking a bit more on this I'm more pro your suggestion since at as of now there is really no way to have a good dynamic default EXCEPT when inside hassio where HASSIO_TOKEN is a normal/default thing.

**Comment by maxandersen** [comment]
updated PR #26 to use http://hass.io/homeassistant and pushed.
