### ISSUE TITLE
HASSIO_TOKEN 401: Unauthorized

### ISSUE THREAD

**Issue by Breakerz** [home-assistant/home-assistant-cli#231]
the token use in the [autocompletion.py](https://github.com/home-assistant/home-assistant-cli/blob/c3a3c7e4b008f71dbf9b6667752aaeabccb343d2/homeassistant_cli/autocompletion.py#L20) only check for **HASS_TOKEN**. When use inside the [SSH & Web Terminal - Community Hass.io Add-on for Home Assistant](https://github.com/hassio-addons/addon-ssh) by @frenck () , it's **HASSIO_TOKEN** instead. 

` hass-cli state get ......error: HomeAssistantCliError: Error while getting all states: 401: Unauthorized`

**Comment by maxandersen** [comment]
wow - weird I haven't catched that sooner. PR open for fix at https://github.com/home-assistant/home-assistant-cli/pull/232

**Comment by maxandersen** [comment]
fixed in dev
