### ISSUE TITLE
Installation problems with homeassistant 0.92.2

### ISSUE THREAD

**Issue by tliron** [home-assistant/home-assistant-cli#243]
It would be nice if they could be installed in the same virtualenv. Right now:
```
pip install --upgrade homeassistant homeassistant-cli
```
Get these errors:
```
ERROR: bellows-homeassistant 0.7.2 has requirement click-log==0.2.0, but you'll have click-log 0.3.2 which is incompatible.
ERROR: homeassistant-cli 0.6.0 has requirement ruamel.yaml==0.15.88, but you'll have ruamel-yaml 0.15.91 which is incompatible.
```

**Comment by maxandersen** [comment]
sorry for troubles; just coming back from travels - have you tried using dev branch ? it has fairly recent dep updates due @fabaff very helpful dependency PR updates :)
I'll try get a new release out to get things more aligned.

**Comment by tliron** [comment]
It's OK, I can use a separate virtualenv for hass-cli. I just thought you would want to know about this, because I imagine most people would want to install the two apps together.

**Comment by fabaff** [comment]
I'm trying to keep the deps in sync but the release cycles are different. Stop pinning the releases could be a way to go for the future.

**Comment by maxandersen** [comment]
Note, 0.7 is released now so do try that. 

@fabaff I reckon we could just pin major version and life would be easier ? Would be nice to at least have a way to build and test on a fixed set though to avoid too many surprises.

**Comment by tliron** [comment]
Thanks, new release 0.7.0 has no dependency conflicts with hass 0.93.1.

My humble recommendation moving forward is to add an integration test for this case, something simple like this:
```
for VERSION in VERSIONS; do
  rm -rf ve
  virtualenv ve
  . ve/bin/activate
  pip install homeassistant==$VERSION /local/something/homeassistant-cli
done
```

**Comment by maxandersen** [comment]
Thanks for checking and your suggestion is interesting but I don't see it catch an issue since at the time of release we are actually compatible with the current homeassistant :)

**Comment by maxandersen** [comment]
If we could get releases more automated or others to help do them we could release the cli more often.

**Comment by maxandersen** [comment]
going forward every push to `dev` releases a dev to pypi if all tests passes.
Thus you can install the latest cli using `pip3 install --pre` 

Additionally release will now be automatically pushed when a version tag are pushed making future releases simpler and way faster to do.
