### ISSUE TITLE
Remove release pinning

### ISSUE THREAD

**Issue by fabaff** [home-assistant/home-assistant-cli#257]
The release pinning is good for us but has at least two major downsides.

- `hass-cli` can't be installed within the same `venv` as Home Assistant. We may have different releases pinned.
- People who are creating distribution packages have to take extra care about the dependencies.

I started to create a Fedora package of `hass-cli` for Fedora 28/29 which I never put up for review. In Fedora 30 is a dependency generator (enabled by default now) taking care about the requirements of the package to provide a smooth user experience. But this will only work if we are not pinning the releases.

I would like to suggest that we remove the strict release pinning.

**Comment by maxandersen** [comment]
I'm +1 for it but is there a way we can at least run build/tests with a specific set of deps while still releasing with open versions ranges ?

IE. I've had to pin deps before to get ci builds not pickup borked deps/build tools.

**Comment by maxandersen** [comment]
would it be sufficient to move to use major minor version open ranges ? i.e. ~=1.2 to indicate anything same or higher than v1.2 but not 1.3 and above ?

**Comment by fabaff** [comment]
I think that we should handle it manually for the time being.
