### ISSUE TITLE
docker installation problem

### ISSUE THREAD

**Issue by MacLe7400** [home-assistant/home-assistant-cli#316]
Hello,

I cannot install docker image of hass-cli on raspbian stretch.

```
$ docker run homeassistant/home-assistant-cli
standard_init_linux.go:211: exec user process caused "exec format error"

```

```
$ uname -a
Linux rasp0 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

```
$ cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs”
```

Any ideas?

**Comment by maxandersen** [comment]
on a PI you would need a armhf build. @fabaff / @balloob #176 hinted it was setup but I don't find any of the armhf builds available on dockerhub.

Do we need to flip a switch somewhere ?

**Comment by MacLe7400** [comment]
Any news related to this issue?

**Comment by balloob** [comment]
Docker only builds x86 containers. There are no arm containers available.

**Comment by maxandersen** [comment]
> Docker only builds x86 containers. There are no arm containers available.

I know the build is not producing them but we have [the armhf docker file](https://github.com/home-assistant/home-assistant-cli/blob/dev/Dockerfile.armhf) and as asked in #176 it would be great to have that enabled in the build so arm containers would be available.

Anything preventing you to enable such builds ?

**Comment by balloob** [comment]
Yeah. It's not that simple. They are built with custom scripts on remote Azure agents via Azure Pipelines. Pascal set it up.
