### ISSUE TITLE
add ha/system commands

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/home-assistant-cli#40]
expose commands to do the typical 'system' level commands.

`config check`
`reload core`
`reload groups`
`reload automations`
`reload all` ? 
`server restart`
`server shutdown`

**Comment by maxandersen** [comment]
https://github.com/home-assistant/hassio/blob/dev/API.md has the api needed.

**Comment by maxandersen** [comment]
might as well just mimic what hassio-cli does https://www.home-assistant.io/hassio/commandline/

**Comment by ldb2000** [comment]
Could be good to have those system commands

**Comment by fabaff** [comment]
Was added with https://github.com/home-assistant/home-assistant-cli/pull/325
