### ISSUE TITLE
consider removing homeassistant dependency

### ISSUE THREAD

**Issue by maxandersen** [home-assistant/home-assistant-cli#42]
currently we depend on homeassistant itself - mainly just to get/share a few constants.

This means a user need to install homeassistant's own dependencies too even though they don't need.

would be nice to avoid that + might be easier to handle mulitple version differences if no hard dep to homeassistant.

**Comment by fabaff** [comment]
If the shared constants are the only reason to depend on `homeassistant` then we should get rid of it. It doesn't make sense to install HA on a client system just because there are some constants shared.

**Comment by maxandersen** [comment]
yup - turned out was a simple fix. no dep on homeassistant in dev branch now.
